### ISSUE TITLE
Question: Why are no simple methods for multiplication exposed?

### ISSUE THREAD

**Issue by codesoap** [teserakt-io/golang-ed25519#1]
I'm not sure if this is the right place for my question, so please just tell me if I came to the wrong address.

I'm playing around with Monero and need functions for scalar multiplication on ed25519 (both with the basepoint and with two scalars). I was surprised not to find functions for that in `crypto/ed25519`, but I also can't find "simple" functions for it in this repository. By "simple" I mean a method which uses `[]byte` as parameters and return value; for example, the [X25519 function from golang.org/x/crypto/curve25519](https://godoc.org/golang.org/x/crypto/curve25519#X25519) looks really easy to use to me - the only thing I find odd about it is the comment "point should be either Basepoint or the output of another X25519 call.", since this would not be the case in some Monero calculations (see [here](https://monerodocs.org/public-address/subaddress/#public-view-key)).

I already learned [here](https://stackoverflow.com/questions/44810708) how to perform multiplication with the basepoint, but I have not yet figured out how to multiply two scalars. Is there a reason for such functions not being implemented in this repository?

**Comment by codesoap** [comment]
Addendum: I think I would even need a function for adding scalars on ed25519, in order to calculate Monero subaddresses (see [here](https://monerodocs.org/public-address/subaddress/#public-spend-key)).

**Comment by diagprov** [comment]
Hello, so, there's probably some terminology confusion here, let me give you a bit of a guide:

 * Curve25519 usually refers to the montomgery-form elliptic curve specified in DJB's paper.
 * X25519 is the usual name for key exchange (elliptic curve diffie hellman) with this curve.
 * Edwards25519 is the name given these days to the (possibly twisted) edwards curve form of Curve25519. There is a birational equivalence between the two, which is a fancy way to say we can map coordinates from one to the other and back with the exception of the points at infinity.
 * Ed25519 is a signature scheme using the twisted edwards form of the curve that is both edwards25519 and curve25519.
 
 The Ed25519 scheme performs signatures, so the API does not give you access to the curve itself for group operations, because this is unnecessary (although partially implemented). 
 
 A word of caution: the X25519 operations as typically implemented to not behave as a proper group, due to scalar clamping. There are a bunch of subtle attacks involved if you aren't careful here.
 
 I think what would suit your needs is https://pkg.go.dev/filippo.io/edwards25519, which implements edwards25519 and multiplication by multiple scalars. 
 
 This library is now unmaintained and you'd be better using this library, or the ed25519 library from the standard library if you need it. Our main reason for using it was the conversion routines to curve25519, which we needed but are straightforward and can be reimplemented with this library if you need them.

Hope that answers your question, good luck.

**Comment by codesoap** [comment]
Thank you for your elaborate answer!

> There is a birational equivalence between the two, which is a fancy way to say we can map coordinates from one to the other and back with the exception of the points at infinity.

I thought I read before, that both curves are not quite the same; thanks for improving my understanding and explaining what "birational equivalence" is. I'll try to inform myself on how such a mapping between the two can be performed.

> I think what would suit your needs is https://pkg.go.dev/filippo.io/edwards25519, which implements edwards25519 and multiplication by multiple scalars.

This looks very promising and I had not found this library on my own. I guess I should start searching pkg.go.dev instead of just GitHub...

> This library is now unmaintained [...]

I wasn't aware of that. Maybe you could mention this in the README or archive this repository to clarify this for people who stumble across this repository.

**Comment by diagprov** [comment]
You might also like to read: https://tools.ietf.org/id/draft-ietf-lwig-curve-representations-02.html, this contains representation conversions for all the curve types (Edwards, Montgomery, Weierstrass).

To speed things up a bit here: Weierstrass form is the general form of an elliptic curve. Short Weierstrass is the usual form that applies to Elliptic Curve crypto. Montgomery form is a special form of Short Weierstrass that allows nice things like the montgomery ladder. Edwards curves are not technically elliptic, but close enough to (and birationally equivalent to) that we can just "ignore" the issue. Twist(ed) is another way of saying "isogenous" i.e. there is a 1-1 map between the forms. 

No worries. There's a lot going on and it isn't always easy to keep up with.

**Comment by codesoap** [comment]
Thanks for the link and your abstract! I'll take a look at draft-ietf-lwig-curve-representations-02 and see if I'm able to understand it.
